name: net_kit

description: "Network Kit is a library that provides a set of tools to work with network requests."

version: 0.1.0

homepage: https://github.com/behzodfaiziev/net_kit
issue_tracker: https://github.com/behzodfaiziev/net_kit/issues
topics:
  - network
  - network-manager

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Core
  equatable: ^2.0.5
  dartz: ^0.10.1

  # Network Manager
  dio: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Code analysis
  very_good_analysis: ^6.0.0
  mocktail: ^1.0.4

flutter: