name: net_kit

description: "Network Kit is a library that provides a set of tools to work with network requests."

version: 0.2.0

homepage: https://github.com/behzodfaiziev/net-kit
issue_tracker: https://github.com/behzodfaiziev/net-kit/issues
topics:
  - network
  - network-manager
  - remote-data
  - dio

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  dartz: ^0.10.1
  dio: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0