name: netkit

description: "Network Manager"

version: 0.9.0

homepage: https://github.com/behzodfaiziev/netkit
issue_tracker: https://github.com/behzodfaiziev/netkit/issues
topics:
  - network
  - network-manager

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Core
  equatable: ^2.0.5
  dartz: ^0.10.1

  # Network Manager
  dio: ^5.6.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  # Code analysis
  very_good_analysis: ^6.0.0

flutter: