name: net_kit

description: "Network Kit is a library that provides a set of tools to work with network requests."

version: 1.5.3

homepage: https://github.com/behzodfaiziev/net-kit
issue_tracker: https://github.com/behzodfaiziev/net-kit/issues
topics:
  - network
  - network-manager
  - remote-data
  - dio

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  dio: ^5.6.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^6.0.0

platforms:
  android:
  ios:
  web:
  linux:
  windows:
  macos:
