name: net_kit

description: "Netkit is a library that provides a set of tools to work with network requests."

version: 2.3.3-dev

homepage: https://github.com/behzodfaiziev/net-kit/tree/main/packages/net-kit
repository: https://github.com/behzodfaiziev/net-kit/tree/main/packages/net-kit
issue_tracker: https://github.com/behzodfaiziev/net-kit/issues
topics:
  - network
  - network-manager
  - remote-data
  - dio

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.7.0
  logger: ^2.4.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^6.0.0
