name: net_kit

description: "Netkit is a library that provides a set of tools to work with network requests."

version: 4.4.4-dev

homepage: https://github.com/behzodfaiziev/net-kit/tree/main/packages/net-kit
issue_tracker: https://github.com/behzodfaiziev/net-kit/issues
repository: https://github.com/behzodfaiziev/net-kit/tree/main/packages/net-kit
funding:
  - https://github.com/sponsors/behzodfaiziev
  - https://buymeacoffee.com/behzodfaiziev

topics:
  - network
  - network-manager
  - remote-data
  - dio

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.8.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.15
  very_good_analysis: ^7.0.0
