name: android_integration_test
description: "Android Integration Test"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  net_kit:
    path: ../packages/net-kit

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  webdriver: ^3.0.3
flutter:
  uses-material-design: true