name: test-my-app

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4

      - uses: futureware-tech/simulator-action@v3
        with:
          model: 'iPhone 14'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter test integration_test
      # You can use flavors to run test, e.g. flutter test integration_test --dart-define=envFlavor=dev --flavor dev
      # Alternatively, if you're using a custom script to run tests, you can use:
      # - run: ./path/to/your/script.sh