# .github/workflows/build-and-test.yml
name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.0

      - name: Install Package dependencies
        run: flutter pub get
        working-directory: packages/net-kit

      - name: Install Flutter Integration Test dependencies
        run: flutter pub get
        working-directory: flutter_integration_test

      - name: Check formatting
        run: dart format --set-exit-if-changed ./packages/net-kit

      - name: Analyze project source
        run: dart analyze --fatal-infos --fatal-warnings

      - name: Run unit tests
        run: dart test
        working-directory: packages/net-kit

  approval:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Approval step
        id: approval_step
        run: echo "Please approve the workflow to continue to iOS tests."
    outputs:
      approved: ${{ steps.approval_step.conclusion == 'success' }}

  test-ios:
    needs: approval
    if: ${{ needs.approval.outputs.approved == 'true' }}
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: futureware-tech/simulator-action@v3
        with:
          model: 'iPhone 14'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
        working-directory: flutter_integration_test

      - name: Run Integration Tests
        run: flutter test integration_test
        working-directory: flutter_integration_test