# This workflow will test the Dart code in the repository
# to make sure that the quality of the code is high.
name: Dart
on:
  push:
    # Run the workflow on the main branch on push
    branches: [ "main" ]
  pull_request:
    # Run the workflow on the main branch on pull requests
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.0
      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Check for formatting issues
      - name: Check formatting
        run: dart format --set-exit-if-changed .

      # Analyze the project source
      - name: Analyze project source
        run: flutter analyze --fatal-infos --fatal-warnings

      # Run test to ensure that the code is working as expected
      - name: Run tests
        run: flutter test

      # Run the integration tests to ensure that the code is working as expected
      - name: Run Dart integration tests
        run: dart test dart_integration_test